MONGODB_SERVER = "127.0.0.1"
MONGODB_PORT = 27017
MONGODB_DBNAME = 'test'
MONGODB_COLLECTION = 'test'

MONGO_CONNECTION = {
    'MONGODB_SERVER': '127.0.0.1',
    'MONGODB_PORT': 27017,
    'MONGODB_DBNAME': 'test',
    'MONGODB_COLLECTION': 'web_pages'
}
